### ISSUE TITLE
Query regarding the testing phase

### ISSUE THREAD

**Issue by LekshmyHari** [blackeagle01/Abnormal_Event_Detection#6]
Thanks for sharing the work. I am bit confused about the testing phase. Couldn't actually decipher when and where the file test.npy which is used in testing phase is produced. In which step are we giving the link for testing videos.

**Comment by LekshmyHari** [comment]
This is the error i am getting while running test.py.

fid = open(file, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'test.npy'

**Comment by blackeagle01** [comment]
@LekshmyHari Do the following:

1. Put all the test videos in one directory.
2. Run processor.py with arguments as the path of the above directory.This will create a test.npy file.
3.  Run test.py pointing to that file.

**Comment by LekshmyHari** [comment]
Got it. Thanks ! 

Would it be possible to output the frame numbers as well on which anomalous activities are detected on each of the test video.

**Comment by blackeagle01** [comment]
@LekshmyHari Sure. Will add a snippet soon.

**Comment by LekshmyHari** [comment]
Much thanks. Was actually looking for having bounding boxes around the activity in an anomalous frame. Would that be practical?

**Comment by blackeagle01** [comment]
@LekshmyHari Yep thats practical but would require an attention mechanism. Will work on it.

**Comment by BalajiB197** [comment]
Hello guys,
I am not able to fig out the issue which i am facing while running preprocess.py with arguments for video path. Issue is for few videos it generates frames but for few other like in my case i am using Avenue dataset of training videos, its not generating any frames.
Help me where i am going wrong.
Thanks,

**Comment by blackeagle01** [comment]
@BalajiB197 The processor.py module selects every video from the directory, extracts frames and stacks them onto a single dump. You can also define the rate at which the frames will be extracted.But only a **single dump** will be created for all the videos in the training/testing directory. Are you sure it is missing some videos?

**Comment by BalajiB197** [comment]
@blackeagle01 Yes am sure. I downloaded Avenue dataset those videos are of avi format, I just changed those format to mp4 and using that as video path arg. Its not saving frames for the files.

**Comment by LekshmyHari** [comment]
Hi,

Would it be possible to share the trained model please? As i am using a CPU machine it is really taking  a lot of time to run 1000 epochs.

**Comment by blackeagle01** [comment]
Use this link[https://drive.google.com/file/d/15byLKcV8ZztZqxB--Pxf_ZsyLUpcQbU7/view?usp=sharing] to download it @LekshmyHari

**Comment by blackeagle01** [comment]
@LekshmyHari Use this [https://drive.google.com/file/d/15byLKcV8ZztZqxB--Pxf_ZsyLUpcQbU7/view?usp=sharing](link)

**Comment by blackeagle01** [comment]
@LekshmyHari Have put up a model.h5 file in the master!

**Comment by LekshmyHari** [comment]
Many thanks for your prompt response. I tested the model (i renamed the model.h5 to AnomalyDetector.h5 which the functions reads) with the avenue test data set which i downloaded from http://www.cse.cuhk.edu.hk/leojia/projects/detectabnormal/dataset.html. But i am facing the following difficulty. Basically all test videos are tested normal which is not the case. Below is the console log. Am i missing something here?

python3 test.py
/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
2018-02-20 09:53:19.321418: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
Bunch Normal
Bunch Normal
Bunch Normal
Bunch Normal
Bunch Normal
Bunch Normal
Bunch Normal
Bunch Normal
Bunch Normal
Bunch Normal
Bunch Normal
Bunch Normal
Bunch Normal
Bunch Normal
Bunch Normal
Bunch Normal
Bunch Normal
Bunch Normal
Bunch Normal
Bunch Normal
Bunch Normal
Bunch Normal
Bunch Normal
Bunch Normal

**Comment by LekshmyHari** [comment]
Did you get a chance to look into this please? Is the shared model file an optimized one?

**Comment by LekshmyHari** [comment]
I tweaked the threshold value a bit and it is working fine now.

**Comment by blackeagle01** [comment]
@LekshmyHari Sorry for the delayed response. Yes tweaking the hyper parameters does the trick! Can you share details about the accuracy?

**Comment by LekshmyHari** [comment]
Thank you for your response.
I am testing using the test videos in avenue dataset. I changed the threshold value to as low as 0.0001 today and all of the test videos are detected as anomalous which is actually correct. But the problem is i tried putting few normal videos in the training folder to the test folder and again tested. Then also everything is detected anomalous(recreated the test.npy file, so that is not the problem). I changed the value of threshold to 0.001 and then every videos are detected as normal. So i think both of these values don't fit. Do you have any recommendations on the threshold value? Have you tried putting normal videos for testing?

**Comment by blackeagle01** [comment]
@LekshmyHari I haven't trained the model myself. I guess the model needs more training on dedicated hardware!

**Comment by LekshmyHari** [comment]
Ok will try to do it on a GPU system in that case.

Did you get a chance to look at the code for frame display and bounding box please?

**Comment by BalajiB197** [comment]
Hello,
I am following the structure, myself using CPU machine (much slow)can you guys provide the dataset of test.npy??

**Comment by blackeagle01** [comment]
@LekshmyHari will look into it after my semester examinations :)

**Comment by LekshmyHari** [comment]
Thank you. I did a bit of testing by tweaking the threshold value using the avenue dataset. I tested by putting all anomalous videos and all normal videos inside the test folder. What i could infer is that the anomalous videos produces a loss value somewhere around 0.0006 and normal videos around 0.0007. I however expected the other way round where the loss value is greater for anomalous videos. By keeping the threshold value at 0.0006 and changing the condition for anomaly as loss < threshold, the testing done is giving somewhat correct results now. Please share your views on this.

I have few more questions please. Your help would be highly appreciated.

1. Whatever testing i have done is on the avenue dataset. Do you have other recommendations for training dataset? I downloaded the UCSD Anomaly Detection Dataset, but the data is in the .tif format and also not in the folder structure which we can call as parameter to processor.py. Please suggest a dataset so that i can try performing training and check if accuracy is increasing.
2. I tried to execute test.py with just one video in the test video directory. I did this to get an insight about threshold value. But it failed with the following error. 

Traceback (most recent call last):
  File "processor_test.py", line 86, in <module>
    a,b,c=imagestore.shape
ValueError: not enough values to unpack (expected 3, got 1)

As i understood from the error, i put 3 videos in that directory and it worked. But it should ideally work for one video as well. What would have went wrong in the code? Below is the code snippet which failed. 

imagestore=np.array(imagestore)
a,b,c=imagestore.shape

3. If we add more layers to the model, is there chances that the accuracy might increase. Please share your opinion.

All the best for your exams !

Regards

**Comment by blackeagle01** [comment]
@LekshmyHari Thank you for personally putting so much effort into it.

About the Datasets: Some recommended datasets have been mentioned in the paper the model is inspired from. I've put a link in the readme.

About the testing error: I will look into the error you're talking about ASAP.

More layers may be added but have to be in accordance with the architecture mentioned in the paper.

**Comment by LekshmyHari** [comment]
Yes, i have seen the description in Readme which is Avenue dataset and in that dataset only i have done the training. As i mentioned in my earlier comment, i tried to use UCSD Anomaly Detection Dataset (which is the other dataset mentioned in the original paper), but had the earlier mentioned issues.

**Comment by LekshmyHari** [comment]
@blackeagle01 did you have any luck with the ValueError mentioned in point 2 please?

**Comment by LekshmyHari** [comment]
This link might help you in finding the error

https://stackoverflow.com/questions/46018062/valueerror-not-enough-values-to-unpack-expected-2-got1

**Comment by LekshmyHari** [comment]
Hi @blackeagle01 could you please tell as to how to display the frame number of the anomalous frame.

**Comment by blackeagle01** [comment]
@LekshmyHari Have made a update to the test module. It will now display the bunch number as well :)

**Comment by Tejaditya** [comment]
I am getting this error on running test.py file.

python test.py


Traceback (most recent call last):
  File "test.py", line 57, in <module>
    model=load_model('AnomalyDetector.h5')
  File "C:\Python36\lib\site-packages\keras\models.py", line 243, in load_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "C:\Python36\lib\site-packages\keras\models.py", line 317, in model_from_config
    return layer_module.deserialize(config, custom_objects=custom_objects)
  File "C:\Python36\lib\site-packages\keras\layers\__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "C:\Python36\lib\site-packages\keras\utils\generic_utils.py", line 144, in deserialize_keras_object
    list(custom_objects.items())))
  File "C:\Python36\lib\site-packages\keras\models.py", line 1372, in from_config
    layer = layer_module.deserialize(conf, custom_objects=custom_objects)
  File "C:\Python36\lib\site-packages\keras\layers\__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "C:\Python36\lib\site-packages\keras\utils\generic_utils.py", line 146, in deserialize_keras_object
    return cls.from_config(config['config'])
  File "C:\Python36\lib\site-packages\keras\layers\convolutional_recurrent.py", line 1067, in from_config
    return cls(**config)
  File "C:\Python36\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "C:\Python36\lib\site-packages\keras\layers\convolutional_recurrent.py", line 945, in __init__
    **kwargs)
  File "C:\Python36\lib\site-packages\keras\layers\convolutional_recurrent.py", line 146, in __init__
    **kwargs)
  File "C:\Python36\lib\site-packages\keras\layers\recurrent.py", line 380, in __init__
    super(RNN, self).__init__(**kwargs)
  File "C:\Python36\lib\site-packages\keras\engine\topology.py", line 293, in __init__
    raise TypeError('Keyword argument not understood:', kwarg)
TypeError: ('Keyword argument not understood:', 'implementation')

**Comment by Tejaditya** [comment]
Update: The error arose because I was using Keras' latest version . Switched back to a previous version , works well.

**Comment by Arfinul** [comment]
How much epoch value i should use?
1 epoch is taking 2 hours approx.
My machine has 8 gb ram

**Comment by AndyHon** [comment]
Hi， @LekshmyHari ，When I run processor. py, there is no frame file generated. How can I solve this problem?thanks

**Comment by Kosam12** [comment]
> Update: The error arose because I was using Keras' latest version . Switched back to a previous version , works well.

i am getting the same error, can you tell me which version you used?

**Comment by harrylei871** [comment]
> @LekshmyHari Have made a update to the test module. It will now display the bunch number as well :)

Thanks for your modification. The code only shows the bunch number, but it's not the same as the frame number tho. How can we know which frame has been detected anomaly? Thanks.
